version: '3'

services:
  web:
    build: .
    command: gunicorn --config gunicorn_config.py backend.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: []