# Generated by Django 4.2.16 on 2024-11-07 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes_app', '0003_remove_note_label_note_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='active_bln',
        ),
        migrations.RemoveField(
            model_name='note',
            name='archive_bln',
        ),
        migrations.RemoveField(
            model_name='note',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='note',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='note',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='note',
            name='pin_bln',
        ),
        migrations.RemoveField(
            model_name='note',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
